language: go
go_import_path: code.cloudfoundry.org/gorouter
go:
  - 1.7
  - tip

matrix:
  allow_failures:
    - go: tip

install:
  - git clone --branch=develop --recurse-submodules https://github.com/cloudfoundry-incubator/routing-release.git $HOME/routing-release
  - export PATH=$HOME/routing-release/bin:$PATH
  - export GOPATH=$GOPATH:$HOME/routing-release

script:
  - ./bin/test
