port: 8083
index: 1
status:
  port: 8084
  user: "user"
  password: "password"
nats:
  uri: "nats://nats:nats@localhost:4222"
logging:
  level: debug
  file: /tmp/router.log
  syslog: vcap.router
  # TODO: add steno web interface
#flush_apps_interval: 30
#go_max_procs: 8
